[tool.poetry]
name = "mssql-spider"
version = "0.4.4"
description = ""
authors = ["dadevel <dadevel@disroot.org>"]
license = "MIT"
packages = [{include = "mssql_spider"}]

[tool.poetry.scripts]
mssql-spider = "mssql_spider.main:main"

[tool.poetry.dependencies]
python = "^3.10"
impacket = {git = "https://github.com/theporgs/impacket.git"}
rich = "^13.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
